# Generated by Django 5.2.8 on 2025-11-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("allergy_id", models.AutoField(primary_key=True, serialize=False)),
                ("allergy_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("ingredient_id", models.AutoField(primary_key=True, serialize=False)),
                ("ingredient_name", models.CharField(max_length=100)),
                (
                    "ingredient_img",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("unit", models.CharField(max_length=20)),
                ("ingredient_category", models.CharField(max_length=50)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("shelf_life", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("password_2", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("is_vegan", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("recipe_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("recipe_img", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "recipe_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fridge",
            fields=[
                ("fridge_id", models.AutoField(primary_key=True, serialize=False)),
                ("f_quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                ("added_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.ingredient",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shopping",
            fields=[
                ("shopping_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("purchased_date", models.DateField()),
                ("added_to_fridge", models.BooleanField(default=False)),
                (
                    "fridge_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="apis.fridge",
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.ingredient",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AllergyIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.allergy"
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.ingredient",
                    ),
                ),
            ],
            options={"unique_together": {("ingredient", "allergy")},},
        ),
        migrations.CreateModel(
            name="PersonAllergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.allergy"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.person"
                    ),
                ),
            ],
            options={"unique_together": {("person", "allergy")},},
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.person"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.recipe"
                    ),
                ),
            ],
            options={"unique_together": {("recipe", "person")},},
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apis.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.recipe"
                    ),
                ),
            ],
            options={"unique_together": {("recipe", "ingredient")},},
        ),
    ]
